version: '3.9'

services:
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate && gunicorn usd_exchange.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_DB_TEST=${REDIS_DB_TEST:-1}
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
